### ISSUE TITLE
🚀 Page: Components

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/mayajs.io#19]
## 📝 Description
This page will contain all the descriptions for Mayajs components. We can also add some code snippets for user to copy. 

## ⚙️ Component
- component

## 📋 Todo:

- [x] Create `Components` page
- [x] Controller section
- [x] Model section
- [x] Services section
- [x] Add "component" route in app routing
- [x] Add "component" route in navigation
