### ISSUE TITLE
🚀Page: `Why MayaJS?`

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/mayajs.io#23]
## 📝 Description

Add a page for describing what is the reason for user why they need to try mayajs.

## ⚙️ Component
-why.component

## 📋 Todo:

- [x] Add why component
- [x] Add headings
     - Easy to use
     - Simplicity
     - Typescript
     - In Between
- [x] Add `why-mayajs` route
- [x] Add sub-routes
    - easy
    - simplicity
    - typescript
    - inbetween
- [x] Add `Why Mayajs` on sidenav
- [x] Add `Previous` button
- [x] Add `Next` button

**Comment by Mackignacio** [comment]
Close #26
